import { z } from 'zod';
import { AIVerbSchema, BaseLadonOrchestrationRequestSchema, GardenArtifactSchema } from './verb_types';

export const IdeatePayloadSchema = z.object({
    temperature: z.number().min(0).max(2).optional().describe("Creativity level (0.0 to 2.0)"),
});
export const IdeateRequestSchema = BaseLadonOrchestrationRequestSchema.extend({
    context: z.string().min(1, "Ideation context is required"),
    verb: z.literal(AIVerbSchema.enum.IDEATE),
    payload: IdeatePayloadSchema,
});

export const IdeateArtifactSchema = GardenArtifactSchema.extend({
    verb: z.literal(AIVerbSchema.enum.IDEATE),
    payload: z.object({
        /** Raw markdown or text generated by xAI LLM. */
        text: z.string(),
        /** Total tokens consumed for use in billing/quota logic */
        tokensUsed: z.number().int().optional(),
    }),
});